### PR TITLE
Added missing second param to postMessage function call

### PR DESCRIPTION
**Pull request by ehlerskon**
Added '*' as second parameter to function calls postMessage

This fixes the error

> Uncaught TypeError: Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.

### CODE REVIEW

**Comment by rodneyrehm** [comment]
interesting, when / where did this become a problem?

**Comment by ehlerskon** [comment]
This error was thrown whenever i used Sass.compile() in my project.

Like the error says, Window.postMessage requires two params. So I added the '*' as a second parameter wherever postMessage is called.

When I have some time, I can try to reproduce the bug in a jsfiddle

**Comment by rodneyrehm** [comment]
thank you!

**Comment by rodneyrehm** [comment]
I'm not sure why this slipped through. Neither of us realized that [Worker.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) does not have an origin, that's only relevant to [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). Your PR actually *breaks* the Sass.js worker API. I'll have to revert this commit…

**Pull request merged**
