### PR TITLE
SASSJS_RELATIVE_PATH when path ../sass.js?1111

### PR DESCRIPTION
**Pull request by fenyagg**

### CODE REVIEW

**Comment by rodneyrehm** [comment]
Thanks for helping to make sass.js better :)

I think we can simplify the path splitting cases, what do you think?

```js
function getBasePath(path, needle) {
  var pos = path.indexOf(needle);
  return pos > -1 ? path.substring(0, pos) : null;
}

var paths = [
  { input: '/foo/bar/sass.js', output: '/foo/bar' },
  { input: '/foo/bar/sass.sync.js', output: '/foo/bar' },
  { input: '/foo/bar/sass.js?cachbuster', output: '/foo/bar' },
  { input: '/foo/bar/sass.sync.js?cachbuster', output: '/foo/bar' },
];

paths.forEach(path => {
  var result = getBasePath(path.input, '/sass.js') || getBasePath(path.input, '/sass.sync.js');
  console.log(path.output === result, result);
});
```

**Comment by fenyagg** [comment]
yes, it better )

**Comment by rodneyrehm** [comment]
did you want to update your PR?

**Comment by fenyagg** [comment]
i can a bit later

**Pull request closed without merging**
